spring.application.name: hook-payment
server:
  port : 8082
  error:
    whitelabel:
      enabled: false
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://dev-34210547.okta.com/oauth2/aushq7x5qzeca3q2s5d7/v1/keys
okta-hook:
  header: ${hook-user}
  password: ${hook-password}
logging:
  level:
    org:
      springframework:
        security: TRACE